bi_ui/views/home.py
from flask import Blueprint, render_template
from flask_login import login_required


home_bp = Blueprint('home_bp', __name__, static_folder='static', template_folder='templates')


@home_bp.route('/', methods=['GET'])
@login_required
def home():
    return render_template('home.html')

bi_ui/views/login.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user


login_bp = Blueprint('login_bp', __name__, static_folder='static', template_folder='templates')


@login_bp.route('/', methods=['GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home_bp.home'))
    return render_template('login.html', error=None)

bi_ui/views/results.py
import logging
from structlog import wrap_logger

from flask import Blueprint, render_template, session, flash
from flask_login import login_required


logger = wrap_logger(logging.getLogger(__name__))


results_bp = Blueprint('results_bp', __name__, static_folder='static', template_folder='templates')


@results_bp.route('/Page/<int:page>', methods=['GET'])
@login_required
def results(page):
    pagination = session['pagination']
    num_results = session['num_results']
    businesses = session['businesses']
    flash([int(num_results), businesses])
    return render_template('results.html', pagination=pagination)

bi_ui/templates/footer.html
<div id="footer">
    <footer class="page__footer">
        <div class="wrapper">
          <div class="group">
            <div class="col-12">
              <span class="pluto">This release is in development. Your <a href="mailto:Register@ons.gov.uk?Subject=User%20feedback"> feedback</a> will help us improve it.</span>
            </div>
          </div>
        </div>
    </footer>
</div>

bi_ui/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <section>
        <div class="main-content">
            <div class="wrapper">
                <div class="group">
                    <div class="col-8">
                        <h2 class="saturn">Search the UK business population</h2>
                        <div class="panel panel--simple panel--info u-mb-l">
                            <p class="mars">To get started, search using one or more of the options below.</p>
                        <div>
                    </div>
                </div>
            </div>
        </div>
        <div class="wrapper">
            <div class="group">
                <div class="col-6">
                    <form class="form" action="http://localhost:5000/api/search_businesses" method="POST">
                        <div class="field u-mb-s">
                            <label class="label">Business name, CRN, VAT, PAYE or UBRN</label>
                            <input autofocus name="BusinessName" class="input input--text input-type__input bi-search-input" type="text" id="name-input">
                        </div>
                        <button class="btn btn--primary venus" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

bi_ui/templates/layout.html
{% import 'macros/paging.html' as paging %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#ffffff">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!-- SDC global styles -->
    <link rel="stylesheet" href="https://cdn.ons.gov.uk/sdc/8f80aaa/css/styles.css">

    <!-- Registers CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/registers-main.css') }}" media="all">

    <title>Business Index</title>
  </head>
  <body>
    <section>
        <header class="page__header">
            <div class="logo_container">
                <div class="wrapper">
                    <div class="group">
                        <div class="col-7">
                            <div class="logo_header">
                                {% if current_user.is_authenticated == True %}
                                    <a href="{{ url_for('home_bp.home') }}">
                                        <img src="{{ url_for('static', filename='img/logo.svg') }}" alt="Office for National Statistics" class="logo__img"/>
                                    </a>
                                {% else %}
                                    <a href="{{ url_for('login_bp.login') }}">
                                        <img src="{{ url_for('static', filename='img/logo.svg') }}" alt="Office for National Statistics" class="logo__img"/>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-5">
                            <div class="header_links">
                                {% if current_user.is_authenticated == True %}
                                    <form id="form-sign-out" action="http://localhost:5000/auth/logout" class="form" method="POST">
                                        <ul class="menubar" role="menubar" id="appmenu">
                                            <li class="menubar" role="menuitem"><button class="logout">Sign out</button></li>
                                        </ul>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="page_title">
                <div class="wrapper">
                    <div class="group">
                        <div class="col-12">
                            <p class="saturn main_heading_sub_page">Business Index</p>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div id="content">{% block content %}{% endblock %}</div>
        {% include 'footer.html' %}
    </section>
  </body>
  <script src="https://cdn.ons.gov.uk/sdc/8f80aaa/scripts/bundle.min.js"></script>
</html>

bi_ui/templates/login.html
{% extends 'layout.html' %}

{% block content %}
  <div class="main-content">
      <div class="wrapper">
          <div class="group">
              <div class="col-12">
                  <form id="form-sign-in" action="http://localhost:5000/auth/login" class="form" method="POST">
                      <h3 class="saturn">Sign in</h3>
                      <div class="field u-mb-s">
                          <label class="label">Username</label>
                          <input autofocus class="input input--text input-type__input" name="username" required type="text">
                      </div>
                      <div class="field">
                          <label class="label " for="inputPassword" id="inputPasswordLabel">Password</label>
                          <div class="field--toggle">
                              <label class="label label--inline venus field__label" for="showPasswordToggle">Show password</label>
                              <input id="showPasswordToggle" class="field__input input input--checkbox" type="checkbox" />
                          </div>
                          <input id="inputPassword" required type="password" name="password" class="input input--text" aria-describedby="inputPasswordLabel" />
                      </div>
                      <p class="forgot-password"><a href="forgot-password.html">Forgot password?</a></p>
                      <button class="btn btn--primary venus" type="submit">Sign in</button>
                      {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for error in messages %}
                                <div class="main-content">
                                    <div class="wrapper">
                                        <div class="group">
                                            <div class="col-8">
                                                <div class="panel panel--simple panel--error u-mb-l">
                                                    <p class="mars">{{ error }}</p>
                                                <div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                      {% endwith %}
                  </form>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

bi_ui/templates/results.html
{% extends 'layout.html' %}

{% block content %}
<section>
    <div class="main-content">
        <div class="wrapper">
            <div class="group">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="col-8">
                    <h1 class="jupiter remove-margin">Search results</h1>
                    {% if messages[0][0] == 1 %}
                    <p class="mars">We've found 1 business</p>
                    {% else %}
                    {% if messages[0][0] >= 10000 %}
                    <div style="display: inline;">
                        <p style="display: inline;">We've found {{ messages[0][0] }} businesses</p>
                        <div style="display: inline-bloc; margin-left: 10px;" class="badge badge--amber">CAPPED</div>
                    </div>
                    {% else %}
                    <p class="mars">We've found {{ messages[0][0] }} businesses</p>
                    <div class="key-line"></div>
                    {% endif %}
                    {% endif %}
                    {% if messages[0][0] >= 10000 %}
                    <br/><br/>
                    <div class="panel panel--warn" style="position: relative;">
                        <div class="panel__header">
                            <div class="venus">Warning</div>
                        </div>
                        <div class="panel__body">
                            <div>Your results have been capped at 10,000, from a total of {{ messages[0][0] }} results
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    <br/>
                    <div>{{ paging.render(pagination) }}</div>
                    {% if messages %}
                    {% for business in messages[0][1] %}
                    <div class="search-item-container">
                        <h3 class="saturn sml-margin">{{ business['BusinessName'] }}</h3>
                        <table class="mars">
                            <tr>
                                <th class="table-grey-text">UBRN</th>
                                <td>{{ business['id'] }}</td>
                            </tr>
                            <tr>
                                <th class="table-grey-text">Post Code</th>
                                <td><a target="_blank"
                                       href="https://www.google.co.uk/maps/place/{{ business['PostCode'].replace(' ', '+') }}">{{
                                    business['PostCode'] }}</a></td>
                            </tr>
                            <tr>
                                <th class="table-grey-text">Industry Code</th>
                                <td>{{ business['IndustryCode'] }}</td>
                            </tr>
                            <tr>
                                <th class="table-grey-text">Trading Status</th>
                                <td>{{ business['TradingStatus'] }}</td>
                            </tr>
                            <tr>
                                <th class="table-grey-text">Legal Status</th>
                                <td>{{ business['LegalStatus'] }}</td>
                            </tr>
                            <tr>
                                <th class="table-grey-text">Employment Band</th>
                                <td>{{ business['EmploymentBands'] }}</td>
                            </tr>
                            <tr>
                                <th class="table-grey-text">Turnover</th>
                                <td>{{ business['Turnover'] }}</td>
                            </tr>
                        </table>
                        <div class="guidance js-details" data-show-label="Show reference numbers"
                             data-hide-label="Hide reference numbers">
                            <a class="guidance__link js-details-trigger js-details-label mars"
                               aria-controls="guidance-answer" aria-expanded="false" id="guidance-trigger"
                               data-guidance-trigger="true" href="#guidance-answer">Show reference numbers</a>
                            <div class="guidance__main js-details-body" id="guidance-answer-body" aria-hidden="true">
                                <div class="guidance__content new">
                                    <table>
                                        {% for vat_ref in business['VatRefs'] %}
                                        <tr>
                                            <th class="table-grey-text-reveal">VAT</th>
                                            <td>{{ vat_ref }}</td>
                                        </tr>
                                        {% endfor %}
                                        {% for paye_ref in business['PayeRefs'] %}
                                        <tr>
                                            <th class="table-grey-text-reveal">PAYE</th>
                                            <td>{{ paye_ref }}</td>
                                        </tr>
                                        {% endfor %}
                                        <tr>
                                            <th class="table-grey-text-reveal">CH</th>
                                            <td>{{ business['CompanyNo'] }}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <br/>
                    <div>{{ paging.render(pagination) }}</div>
                    {% endif %}
                </div>
                {% else %}
                <h1 class="jupiter remove-margin">Search results</h1>
                <div class="main-content">
                    <div class="wrapper">
                        <div class="group">
                            <div class="col-8">
                                <div class="panel panel--simple panel--error u-mb-l">
                                    <p class="mars">Please submit a search before navigating to the Results page.</p>
                                    <div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% endwith %}
                    </div>
                </div>
            </div>
</section>
{% endblock %}